I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 33, in script call
    call at_home
  File "game/at_home.rpy", line 57, in script call
    call travelling
  File "game/functions.rpy", line 38, in script
    return
Exception: Could not find return label ('game/uu_campus.rpy', 1681833433, 19).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 33, in script call
    call at_home
  File "game/at_home.rpy", line 57, in script call
    call travelling
  File "game/functions.rpy", line 38, in script
    return
  File "C:\Users\Geertje\Documents\Utrecht\Master Thesis\02_Second_phase\High-fi_prototype\renpy-8.0.3-sdk\renpy\ast.py", line 1782, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "C:\Users\Geertje\Documents\Utrecht\Master Thesis\02_Second_phase\High-fi_prototype\renpy-8.0.3-sdk\renpy\execution.py", line 726, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label ('game/uu_campus.rpy', 1681833433, 19).

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Diverse Perspectives 1.0
Fri Apr 21 14:55:33 2023
