I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 33, in script call
    call at_home
  File "game/at_home.rpy", line 103, in script call
    call travelling
  File "game/travelling.rpy", line 56, in script call
    call dilemma1
  File "game/travelling.rpy", line 178, in script call
    call uu_campus
  File "game/uu_campus.rpy", line 371, in script call
    call lecture_room
  File "game/lecture_room.rpy", line 269, in script
    val "{i}\“That went well. I’m glad I found a group so quickly.\”{/i}"
Exception: Sayer 'val' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 33, in script call
    call at_home
  File "game/at_home.rpy", line 103, in script call
    call travelling
  File "game/travelling.rpy", line 56, in script call
    call dilemma1
  File "game/travelling.rpy", line 178, in script call
    call uu_campus
  File "game/uu_campus.rpy", line 371, in script call
    call lecture_room
  File "game/lecture_room.rpy", line 269, in script
    val "{i}\“That went well. I’m glad I found a group so quickly.\”{/i}"
  File "C:\Users\Geertje\Documents\Utrecht\Master Thesis\02_Second_phase\High-fi_prototype\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Geertje\Documents\Utrecht\Master Thesis\02_Second_phase\High-fi_prototype\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'val' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Diverse Perspectives 1.0
Thu Apr 20 11:59:10 2023
