I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 32, in script call
    call at_home
  File "game/at_home.rpy", line 147, in script
    if breakfast == "hagelslag":
  File "game/at_home.rpy", line 147, in <module>
    if breakfast == "hagelslag":
NameError: name 'breakfast' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 32, in script call
    call at_home
  File "game/at_home.rpy", line 147, in script
    if breakfast == "hagelslag":
  File "C:\Users\Geertje\Documents\Utrecht\Master Thesis\02_Second_phase\High-fi_prototype\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Geertje\Documents\Utrecht\Master Thesis\02_Second_phase\High-fi_prototype\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Geertje\Documents\Utrecht\Master Thesis\02_Second_phase\High-fi_prototype\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/at_home.rpy", line 147, in <module>
    if breakfast == "hagelslag":
NameError: name 'breakfast' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Diverse Perspectives 1.0
Mon Apr 17 11:51:26 2023
